### ISSUE TITLE
Suppport windows 10 other languages 

### ISSUE THREAD

**Issue by Racoon005** [TheJoeFin/Text-Grab#31]
The application hangs when running on windows 10 with other language than English (I suppose but at least using french).
Can be specific of english version with MUI.

Here is the .NET Runtime error reported in log :
Application: Text-Grab.exe
CoreCLR Version: 4.700.20.47201
.NET Core Version: 3.1.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException: Method not found: 'System.String Windows.Globalization.Language.get_AbbreviatedName()'.
   at Text_Grab.MainWindow.<>c__DisplayClass14_0.<ExtractText>b__1(Language la)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Text_Grab.MainWindow.ExtractText(Bitmap bmp, String languageCode, Nullable`1 singlePoint)
   at Text_Grab.MainWindow.GetRegionsText(Rectangle selectedRegion)
   at Text_Grab.MainWindow.RegionClickCanvas_MouseUp(Object sender, MouseButtonEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Text_Grab.App.Main()

Here is the Application Error :
Nom de l’application défaillante Text-Grab.exe, version : 0.0.0.0, horodatage : 0x5f6b3846
Nom du module défaillant : KERNELBASE.dll, version : 10.0.17763.1790, horodatage : 0x16e07148
Code d’exception : 0xe0434352
Décalage d’erreur : 0x001226c2
ID du processus défaillant : 0x41f8
Heure de début de l’application défaillante : 0x01d73214e3607b4a
Chemin d’accès de l’application défaillante : C:\Program Files\WindowsApps\40087JoeFinApps.TextGrab_1.5.0.0_x86__kdbpvth5scec4\Text-Grab\Text-Grab.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : 489e2446-6ba1-44da-8f6b-fa05418c7c7e
Nom complet du package défaillant : 40087JoeFinApps.TextGrab_1.5.0.0_x86__kdbpvth5scec4
ID de l’application relative au package défaillant : App

Switching windows 10 to English make it works.
Available for translation of the error above if needed.

**Comment by TheJoeFin** [comment]
@Racoon005 Were you building Text Grab from Visual Studio when you got this error or were you running the installed app from the Microsoft Store?

**Comment by Racoon005** [comment]
@TheJoeFin Installed App from the Microsoft Store.

**Comment by TheJoeFin** [comment]
@Racoon005 I just tested Text Grab with French and it seems to be working fine. Can you send a screenshot of your Language page in Windows 10 settings. This is what mine looks like:
![image](https://user-images.githubusercontent.com/7809853/115090675-1a3a8000-9edb-11eb-9bb7-1db05ddc529d.png)

**Comment by Racoon005** [comment]
This config create the exception : 
![TextGrabFr](https://user-images.githubusercontent.com/82604756/115104952-58c44f00-9f5c-11eb-89dc-61f4638ba03d.png)

**Comment by Racoon005** [comment]
@TheJoeFin this one works fine : 
![TextGrabEn](https://user-images.githubusercontent.com/82604756/115105281-3a5f5300-9f5e-11eb-8a08-59bb48e70720.png)

I expect to use TextGrab on my company computer which is an English W10 master with country based language package if this can help...

**Comment by Racoon005** [comment]
![TextGrabWinVer](https://user-images.githubusercontent.com/82604756/115105402-ed2fb100-9f5e-11eb-852a-1e300706e1ec.png)

**Comment by Racoon005** [comment]
@TheJoeFin Some more information to help diagnose.
- The application launches correctly.
- I can select the text to be OCR 
- then the screen freezes and the app hangs.
Available for a call to show you the issue if you need. Feel free to ask for.

**Comment by Racoon005** [comment]
@TheJoeFin I made some new tests today and the textgrab works well even with french text but I need to have  the windows 10 UI in english. This bug looks not related to the language of the text itself.

**Comment by TheJoeFin** [comment]
@Racoon005 part of the problem may be that you do not have the other language features installed on your computer:
![image](https://user-images.githubusercontent.com/7809853/115250502-41699b00-a0ef-11eb-9cf9-21418979ad8d.png)

English has 

- Language pack
- Text-to-speech
- Speech recognition 
- Handwriting
- Basic typing with spellcheckers and dictionaries 

French has

- Language pack

Try to install the other language features for French.

**Comment by TheJoeFin** [comment]
@Racoon005 Any update on this issue? Did you try installing more features to the French language?

**Comment by lcorb** [comment]
Getting a similar issue when building in Visual Studio:
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String Windows.Globalization.Language.get_AbbreviatedName()'.
  Source=Text-Grab
  StackTrace:
   at Text_Grab.ImageMethods.<>c__DisplayClass5_0.<ExtractText>b__1(Language la)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Text_Grab.ImageMethods.<ExtractText>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Text_Grab.ImageMethods.<GetRegionsText>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Text_Grab.Views.FullscreenGrab.<RegionClickCanvas_MouseUp>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Text_Grab.App.Main()
```

My language is set to English (Australia), and keyboard to English (Australia). Interestingly, the application seems to encounter this crash if the keyboard layout is not set to English (United States). I can run the application perfectly fine with this keyboard layout, and I have no issues when the language is set to English (Australia).

**Comment by TheJoeFin** [comment]
I believe this has been closed. Test with 2.3 preview, if this issue remains please reopen.

**Comment by Racoon005** [comment]
Works now ! Well done, thanks.
